version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "CircleCIApp/build.gradle" }}-{{ checksum  "CircleCIApp/app/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./CircleCIApp/gradlew
      - run:
          name: Download Dependencies
          command: ./CircleCIApp/gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "CircleCIApp/build.gradle" }}-{{ checksum  "CircleCIApp/app/build.gradle" }}
      - run:
          name: Run Build
          command: ./CircleCIApp/gradlew assembleDebug
      - store_artifacts:
          path: CircleCIApp/app/build/outputs/apk/debug/
          destination: artifact-file